#+LATEX_CLASS: moderncv
#+CVSTYLE: moderncv
#+CVCOLOR: blue
#+LaTeX_HEADER: \input{/home/daniel/Desktop/myCv/MyTeXHeader.tex}


#+MOBILE: +351 919333939
# #+HOMEPAGE: example.com
# #+ADDRESS: Rua da Fonte 18
# #+ADDRESS: 3515-717 Calde
# #+ADDRESS: Almargem Viseu
# #+GITLAB: BigNaNet
#+GITHUB: BigNaNet
#+LINKEDIN: daniel-ferreira
#+PHOTO: myFface.png
# #+QUOTE: Life can only be understood backwards, but it must be lived forwards  -Soren Kierkegaard

#+TITLE:  Physics Engineer
#+AUTHOR: Daniel Ferreira
#+email: ferreira.d4.r@gmail.com
* Master thesis                                                    :noexport:
** Diminishing peak occurrences in Household-grid exchanges
:PROPERTIES:
:CV_ENV: cvthesis
:description: SuperComputing Systems AG
:END:
* Experience
** Operational Forecast Engineer
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2019-10-22>
:TO:
:LOCATION: Porto, Portugal
:EMPLOYER: Vestas
:END:
I further apply  the knowledge gained previously, got acquinted with state of the art technologies such as Containerization,
CI/CD processes, and Kubernetes while working under Agile methodologies.
** Operational Forecast Engineer Trainee
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2018-10-22>
:TO:       <2019-10-21>
:LOCATION: Porto, Portugal
:EMPLOYER: Vestas
:END:
This Position had me in a team that was responsible for a fully running forecast system. I got in touch with
machine learning algorithms, linux systems, relational databases and  python scripting.
* Education
**  Master
:PROPERTIES:
:CV_ENV: cventry
:FROM:
:TO:
:LOCATION: Coimbra
:EMPLOYER: University of Coimbra
:END:
* Skills
# *** one
# :Properties:
# :CV_ENV: cvdoubleitem
# :SKILL1: Emacs
# :LEVEL1: 3
# :END:
*** two
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Python
:LEVEL1: 4
:END:
*** Three
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Kubernetes
:LEVEL1: 2
:END:
*** FOur
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Git
:LEVEL1: 3
:END:
*** Five
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Prometheus
:LEVEL1: 2
:END:
*** six
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: MySQL
:LEVEL1: 2
:END:
*** seven
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: docker
:LEVEL1: 2
:END:
*** eight
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: CI/CD
:LEVEL1: 2
:END:
*** nine
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Machine Learning
:LEVEL1: 2
:END:
*** Ten
:Properties:
:CV_ENV: cvdoubleitem
:SKILL1: Agile Methodologies
:LEVEL1: 2
:END:

* Languages
** Portuguese
:Properties:
:CV_ENV: language
:SKILL: 5
:END:
** English
:Properties:
:CV_ENV: language
:SKILL: 4
:COMMENT: My current work environment has English as its main language.
:END:
** German
:Properties:
:CV_ENV: language
:SKILL: 4
:COMMENT: I'm able to have a fluent conversation in German
:END:
** French
:Properties:
:CV_ENV: language
:SKILL: 1
:END:
* Volunteer
** Scout Monitor
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2016-09-22>
:TO:
:LOCATION: Viseu, Portugal
:EMPLOYER: CNE, WOSM
:END:

** Vogal, Nucleo de Estudantes do Departamento de Física
:PROPERTIES:
:CV_ENV: cventry
:FROM:     <2013-10-22>
:TO: <2014-07-11 qui>
:LOCATION: Coimbra, Portugal
:EMPLOYER: Associação Académica de Coimbra
:END:

* Hobbies
  Currently they are raspberrypi, python and emacs.
  I really like to hike, read and learn new things, in-between I play the piano
* Letter                                                           :noexport:
:PROPERTIES:
:CV_ENV: letter
:RECIPIENT: Piotr Nowalinski
:RECIPIENT2: Zhülke Engineering AG  \\ Wiesenstrasse 10a \\ Zhürich
:OPENING:  Dear Mr. Piotr Nowalinski
:DATE: <2019-07-30 ter>
:END:
I am interested in the Junior DevOp position advertised in your website. Given my
related experience and capacity to learn, I would appreciate your consideration
for this job opening.

Having earned my Master in Physics Engineering from Coimbra University, I have
been exposed to a vibrant knowledge environment where learning was always
encouraged and seen as the best knowledge gained.

I have  already experienced this advantage as I joined Vestas as an
Operational Forecast Engineer where I face daily new challenges,
technical as well as in comunication.

Since I started at Vestas, I found myself exposed to a fully operating system
that needs nurture and quick solutions when problems rise. This allowed me to
work in a fast working environment and solution driven, as customers where
expecting the system to be fully operational. The contact with the forecasting
system allowed me to be emersed in an linux environment and develop my scripting capabilities,
specially in the Python language.

I have been exposed to  CI/CD pipelines as well
as k8s environments, where I am currently working on the monitoring
Infrastructure which alllows me to work with tools such as Prometheus, elasticsearch,
 and the alerting conterparts.

I enjoy to learn new technologies as well as new ways of solving problems. I
belive that all the previous considerations qualify me for this position. I
look forward to discussing how my set of skills can be of value to Zhülke.

Thank you for your time, consideration and forthcoming response.

* Run me                                                           :noexport:
#+BEGIN_SRC emacs-lisp
(Org-export-to-file 'moderncv "DanielFerreira.tex")
(org-latex-compile "DanielFerreira.tex")
#+END_SRC

#+RESULTS:
: /home/daniel/Desktop/myCv/DanielFerreira.pdf
